### ISSUE TITLE
Add more comparison benchmarks

### ISSUE THREAD

**Issue by mattbasta** [mattbasta/crass#19]
- [csso](https://github.com/css/csso)
- [cssshrink](https://github.com/stoyan/cssshrink)

Update clean-css benchmark

**Comment by ben-eb** [comment]
Might be worth just linking to the [extensive benchmarks posted by GoalSmashers](https://github.com/GoalSmashers/css-minification-benchmark). I've sent a PR for this module to be added to their list. https://github.com/GoalSmashers/css-minification-benchmark/pull/33

**Comment by mattbasta** [comment]
Good call. I hadn't seen the project. In running the benchmarks, I found a few bugs and have a few new optimizations in the pipeline. Good stuff, thanks!

**Comment by ben-eb** [comment]
`0.7.4` looks great! PR has been merged, you can have a look at the new benchmark here http://goalsmashers.github.io/css-minification-benchmark/ :smile:
