### ISSUE TITLE
Merge duplicate @media rules

### ISSUE THREAD

**Issue by JacobEvelyn** [mattbasta/crass#58]
My build chain produces CSS that looks like this:

```
.foo {
  color: "#333";
}
.bar {
  color: "#ddd";
}
@media screen and (max-width:50pc) {
  .foo {
    color: "#444";
  }
}
@media screen and (max-width:50pc) {
  .bar {
    color: "#eee";
  }
}
```

I noticed that `crass` doesn't combine the two `@media` rules into a single one. Is that something others would value? Should I look at the code and try to come up with a pull request?

**Comment by mattbasta** [comment]
Thanks for the issue! Let me take a quick look and see if it's something I can knock out fast.

**Comment by JacobEvelyn** [comment]
Amazing, thanks!

**Comment by soluml** [comment]
@mattbasta Thoughts on taking this same logic and applying it to `@supports`?

**Comment by mattbasta** [comment]
@soluml Can you file a new issue? I'm rewriting everything in TypeScript, and I can include this in the final rewrite.
