### ISSUE TITLE
Clarify in docs what CSS 4 features / modern browser requirements are needed

### ISSUE THREAD

**Issue by sanmai-NL** [mattbasta/crass#66]
Could you please explain a bit which browser versions will have issues with `--css4`?

I couldn't find much with ‘CSS 4’-like queries on caniuse.com.

**Comment by mattbasta** [comment]
Basically all of them will have problems. No major browsers have support for all of the CSS4 features that Crass can generate. You should only use that option if you intentionally want CSS4 output.
